#!/usr/bin/env python3
"""Write LandingPageDeploy/privacy.html from the in-app policy, so the two never drift.

The source of truth is `LullPrivacyViewController.sections` and `effectiveDate` in
App/Shared/ParentInfoViewController.swift, with `LullLinks.supportEmail` filled in.
Run after editing the policy:  python3 Tools/Store/build_privacy_page.py
"""
import html
import re
from pathlib import Path

root = Path(__file__).resolve().parents[2]
swift = (root / "App/Shared/ParentInfoViewController.swift").read_text()
email = re.search(r'static let supportEmail = "([^"]+)"', swift).group(1)
date = re.search(r'static let effectiveDate = "([^"]+)"', swift).group(1)
block = swift.split("static var sections: [(String, String)] {", 1)[1].split("\n    }\n", 1)[0]
pairs = re.findall(r'\(\s*"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)"\s*\)', block, re.S)
assert len(pairs) >= 6, "could not read the policy sections"


def fill(text):
    text = text.replace("\\(LullLinks.supportEmail)", email).replace("\\(effectiveDate)", date)
    assert "\\(" not in text, text
    escaped = html.escape(text)
    return escaped.replace(html.escape(email), f'<a href="mailto:{email}">{email}</a>')


sections = "\n".join(f"      <h2>{fill(h)}</h2>\n      <p>{fill(b)}</p>" for h, b in pairs)
page = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Privacy — Lull</title>
  <meta name="description" content="Lull collects no data about you or your child.">
  <meta name="theme-color" content="#F8F3E9">
  <link rel="icon" href="assets/icon-64.png">
  <link rel="apple-touch-icon" href="assets/icon-180.png">
  <link rel="stylesheet" href="site.css">
</head>
<body>
  <div class="wrap narrow">
    <header class="site">
      <a class="brand" href="./"><img src="assets/icon-64.png" alt=""><span>Lull</span></a>
      <nav class="site"><a href="support.html">Support</a><a href="privacy.html" aria-current="page">Privacy</a></nav>
    </header>
    <main class="doc">
      <!-- Generated by Tools/Store/build_privacy_page.py from the in-app policy. Edit the Swift, not this file. -->
      <h1>Privacy</h1>
      <p class="date">Lull for iPhone and iPad · Effective {html.escape(date)}</p>
{sections}
      <h2>This website</h2>
      <p>This site sets no cookies and loads no analytics, ads, or third-party fonts or scripts. Our host may keep standard server logs (such as IP address and time of visit) for security, which we do not use to identify anyone.</p>
    </main>
    <footer class="site">
      <p><a href="./">Home</a> · <a href="support.html">Support</a> · <a href="mailto:{email}">{email}</a></p>
    </footer>
  </div>
</body>
</html>
'''
(root / "LandingPageDeploy/privacy.html").write_text(page)
print(f"privacy.html: {len(pairs)} sections, contact {email}, effective {date}")
